backend:
  name: github
  repo: phamhuutri108/portfolio-phamhuutri
  branch: main
  base_url: https://oauth-server.phamhuutri108.workers.dev
  auth_endpoint: auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "short_films"
    label: "Phim Ngắn"
    folder: "content/short-films"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Mã Phim (ID)", name: "uid", widget: "string", hint: "Ví dụ: dad-dont-lie-to-me"}
      - {label: "Tựa đề (Tiếng Việt)", name: "title_vi", widget: "string"}
      - {label: "Tựa đề (Tiếng Anh)", name: "title_en", widget: "string"}
      - {label: "Ảnh Bìa", name: "thumbnail", widget: "image"}
      - {label: "Nội dung (Tiếng Việt)", name: "body_vi", widget: "markdown"}
      - {label: "Nội dung (Tiếng Anh)", name: "body_en", widget: "markdown"}